# Generated by Django 4.2.6 on 2023-12-08 18:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_datosextra_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='biografia',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
