# Generated by Django 4.2.6 on 2023-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.TextField()),
                ('fecha_de_creacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Televisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.TextField()),
                ('fecha_de_creacion', models.IntegerField()),
            ],
        ),
    ]
